
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: treasurehunt_development

test:
  <<: *default
  database: treasurehunt_test

production:
  <<: *default
  database: treasurehunt_production
  username: treasurehunt
  password: <%= ENV['TREASUREHUNT_DATABASE_PASSWORD'] %>
